
#Make test creates a driver to test the question making Function
#and the topics generated
test: questions.o topics.o answers.o
	g++ -o test questions.cpp questions.hpp topics.cpp topics.hpp answers.cpp answers.hpp
